### ISSUE TITLE
Missing test load when running test files

### ISSUE THREAD

**Issue by GasolLY** [DICL/listdb#11]
Hello. I managed to compile the code file by adding the cmake parameter. But when I run the test file, it prompts that the test load is missing.
![image](https://user-images.githubusercontent.com/23418283/217136717-8be3a898-8f57-4dd8-a6dd-0024afff8381.png)

I found the definition #define LOAD_FILE in the string_kv_test.cc file，but dont have the file。
![image](https://user-images.githubusercontent.com/23418283/217136986-2f03f0ab-92d4-43ee-bf5f-d5ee8c5cd3c2.png)

**Comment by wonbaekimys** [comment]
Hi GasolLY,
Sorry for the late reply.
You can use index-microbench to generate workload files.
[index-microbench](https://github.com/wangziqi2016/index-microbench)
They provide instructions on how to generate workload files.

**Comment by GasolLY** [comment]
> Hi GasolLY, Sorry for the late reply. You can use index-microbench to generate workload files. https://github.com/wangziqi2016/index-microbench They provide instructions on how to generate workload files.

Thanks for your answer.But when I tried to run the project against the readme to generate the load, I found that the name and type of the generated load did not seem to match my expectation.

The generated workload：
![image](https://user-images.githubusercontent.com/23418283/217792120-6047e107-d40b-4fd2-84e3-69cdd8eb4080.png)

The name of workload in your project：
![image](https://user-images.githubusercontent.com/23418283/217792668-634cb11a-2f82-4322-9245-6f86b513b862.png)

**Comment by GasolLY** [comment]
> Hi GasolLY, Sorry for the late reply. You can use index-microbench to generate workload files. https://github.com/wangziqi2016/index-microbench They provide instructions on how to generate workload files.

Other than that, have you tested the data on the latency of ListDB? This would be very useful for me, thank you.
