### ISSUE TITLE
Compiling Error: Cannot find libpmemobj++/pexceptions.hpp

### ISSUE THREAD

**Issue by SHTUSIST** [DICL/listdb#9]
`/xxx/listdb/listdb.h:16:10: fatal error: libpmemobj++/pexceptions.hpp: No such file or directory

 #include <libpmemobj++/pexceptions.hpp>
`

I have installed the newest version and I could run other programs using libpmemobj

`libpmem-dev is already the newest version (1.8-1ubuntu1).
libpmemblk-dev is already the newest version (1.8-1ubuntu1).
libpmemlog-dev is already the newest version (1.8-1ubuntu1).
libpmemobj-dev is already the newest version (1.8-1ubuntu1).
libpmempool-dev is already the newest version (1.8-1ubuntu1).
librpmem-dev is already the newest version (1.8-1ubuntu1).
`

Sorry to bother you. Could you give some hints?

**Comment by wonbaekimys** [comment]
Hi SHTUSIST, sorry for the late reply.
Version issues always bother us.
I tried to check the version I ran, but it's not going well.
[https://github.com/pmem](https://github.com/pmem)
You might want to look for a version that includes _pexceptions.hpp_ from the link above and try installing it.
